linkPrefix = "/contracts"
name = "librebank-contracts"
version = "0.0.1"
description = "LibreBank emission and token contracts"
buildTime = 2018-03-20T09:41:15.460Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "decodedbrain, scientistnik, evercodex"
homepage = "https://librecash.github.io/contracts/docs/ComplexExchanger"
license = "AGPL-3.0"

[interaction]